spring.application.name=bank-project
spring.datasource.url=jdbc:mysql://localhost:3306/bank
spring.datasource.username=root
spring.datasource.password=Umut2027!Db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=u
spring.security.user.password=1

# JWT için en az 256-bit (32 karakter veya daha uzun) güvenli bir anahtar belirleyin
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Hata oluştuğunda tüm Stack Trace'i konsola basar
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Eğer GlobalExceptionHandler veya ControllerAdvice loglarını görmek isterseniz:
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=DEBUG
